poles_list = [
  {
    name: "Personel",
    id: 4,
  },
  ,
  {
    name: "electriciter",
    id: 1,
  },
  {
    name: "eau",
    id: 2,
  },
  {
    name: "Danger",
    id: 3,
  },
];

let Utilisateurs = [
  ["ahere", "Hère", "Axel", "axel.here@betuf.fr", "abcde", "Directeur", ""],
  [
    "vroule",
    "Roule",
    "Vanessa",
    "vanessa.roule@betuf.fr",
    "abcde",
    "Directeur recherche",
    "",
  ],
  [
    "vsunnick",
    "Sunnick",
    "Vincent",
    "vincent.sunnick@betuf.fr",
    "abcde",
    "Secrétaire général",
    "",
  ],
  [
    "gtaie",
    "Taie",
    "Gilbert",
    "gilbert.taie@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Constructio, Marchés, Exécution",
  ],
  [
    "jvoilbout",
    "Voilbout",
    "Jean",
    "jean.voilbout@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Géologie, Géothermie",
  ],
  [
    "lvragedar",
    "Vragedar",
    "Louis",
    "louis.vragedar@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Matériaux, structure",
  ],
  [
    "athinerairebis",
    "Thinérairebis",
    "Ali",
    "ali.thinerairebis@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Ventilation et Environnement",
  ],
  [
    "adoublesens",
    "Doublesens",
    "Angela",
    "angela.doublesens@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Sécurité",
  ],
  [
    "ofour",
    "Four",
    "Oscar",
    "oscar.four@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Exploitation",
  ],
  [
    "rtaurout",
    "Taurout",
    "Roméo",
    "romeo.taurout@betuf.fr",
    "abcde",
    "Chef de pôle",
    "Equipements électriques et gestion",
  ],
  [
    "atoutdroit",
    "Toudroit",
    "Alphonse",
    "alphonse.toudroit@betuf.fr",
    "abcde",
    "Chargé de missions",
    "",
  ],
  [
    "apartemental",
    "Partemental",
    "Amédée",
    "amedee.partemental@betuf.fr",
    "abcde",
    "Chargé de missions",
    "",
  ],
  [
    "afrastructure",
    "Frastructure",
    "Alain",
    "alain.frastructure@betuf.fr",
    "abcde",
    "Chargé de missions",
    "",
  ],
  [
    "vdevaux",
    "Devaux",
    "Valérie",
    "valerie.devaux@betuf.fr",
    "abcde",
    "Chargé de missions",
    "",
  ],
  [
    "ajohn",
    "John",
    "Aline",
    "aline.john@betuf.fr",
    "abcde",
    "Chargé de missions",
    "",
  ],
  [
    "lrection",
    "Rection",
    "Lydie",
    "lydie.rection@betuf.fr",
    "abcde",
    "Chargé de missions",
    "",
  ],
  [
    "jdoe",
    "Doe",
    "Jane",
    "jane.doe@betuf.fr",
    "abcde",
    "Technicien",
    "Sécurité",
  ],
];
